language: php

php:
  - 5.4

env:
    - WP_VERSION=master WP_MULTISITE=0

addons:
  hosts:
    - wordpress.dev

before_install:
  - sudo apt-get update > /dev/null
  - composer self-update

install:


before_script:
  - ./ci/prepare.sh

script:
  # Create display.
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  - sleep 3 # give xvfb some time to start

#  - composer update --no-interaction --prefer-dist
#  - sudo /etc/init.d/apache2 restart
#  - cat /etc/apache2/sites-enabled/000-default
##  - cat /etc/apache2/apache2.conf
#  - cat /etc/apache2/conf.d/*.conf
#  - pwd
#  - ls -alh ..
#  - ls -alh bin
#  - ls -alh vendor
#  - ./bin/wp core download
#  - ls -alh
#
#  - curl -s localhost
#  - ./bin/wp eval "echo ABSPATH . PHP_EOL;"

  # Run selenium.
#  - wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar
#  - java -jar selenium-server-standalone-2.45.0.jar -p 4444 > ~/selenium.log 2>&1 &
#  - sleep 5

  # Run phantomJs.
#  - phantomjs --webdriver=4444 > ~/phantomjs.log 2>&1 &

  # Run behat tests.
#  - ls -alh
#  - ls -alh ..
#  - cd ../behat
#  - ./bin/behat --tags=~@wip

  # Print log ~/phantomjs.log
#  - cat ~/phantomjs.log

  # Print log ~/selenium.log
#  - cat ~/selenium.log
