language: php

php:
  - 5.4

env:
    - WP_VERSION=master WP_MULTISITE=0

before_install:
  - sudo apt-get update > /dev/null
  - composer self-update

install:
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

before_script:
  - echo 'date.timezone = "Europe/London"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  # Create display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

  # Run selenium.
  - wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar
  - java -jar selenium-server-standalone-2.45.0.jar -p 4444 > ~/selenium.log 2>&1 &
  - sleep 5

  # Run phantomJs.
  - phantomjs --webdriver=4444 > ~/phantomjs.log 2>&1 &

  # Run behat tests.
  - cd ../behat
  - ./bin/behat --tags=~@wip

  # Print log ~/phantomjs.log
  - cat ~/phantomjs.log

  # Print log ~/selenium.log
  # - cat ~/selenium.log
