language: php

php:
  - 5.4

env:
    - WP_VERSION=master WP_MULTISITE=0

addons:
  hosts:
    - local.wordpress.dev

before_install:
  - sudo apt-get update > /dev/null
  # These variables have to be set here, so they can be used by
  # prepare.sh as well as the commands in the script block below
  - export WORDPRESS_SITE_DIR="$(dirname $TRAVIS_BUILD_DIR)/wordpress/"
  - export WORDPRESS_TEST_SUBJECT=$(basename $TRAVIS_BUILD_DIR)
  - export WP_CLI="${TRAVIS_BUILD_DIR}/vendor/bin/wp"
  - export WORDPRESS_FAKE_MAIL_DIR="$(dirname $TRAVIS_BUILD_DIR)/fake-mail/"
  - export SELENIUM_PORT=4444
  - ./ci/prepare.sh

install:


before_script:

script:

  # Run behat tests.
  - ${WORDPRESS_SITE_DIR}/wp-content/plugins/${WORDPRESS_TEST_SUBJECT}/vendor/bin/behat -c $WORDPRESS_SITE_DIR/wp-content/plugins/${WORDPRESS_TEST_SUBJECT}/behat.yml

  # Print log ~/phantomjs.log
#  - cat ~/phantomjs.log

  # Print log ~/selenium.log
#  - cat ~/selenium.log
