language: php

php:
  - 5.4

env:
    - WP_VERSION=master WP_MULTISITE=0

addons:
  hosts:
    - local.wordpress.dev

before_install:
  - sudo apt-get update > /dev/null
  - export WORDPRESS_SITE_DIR="$(dirname $TRAVIS_BUILD_DIR)/wordpress/"
  - export WORDPRESS_TEST_SUBJECT=$(basename $TRAVIS_BUILD_DIR)
  - export WP_CLI="${TRAVIS_BUILD_DIR}/vendor/bin/wp"
  - ./ci/prepare.sh

install:


before_script:

script:
  - curl -s http://local.wordpress.dev/wp-content/plugins/${WORDPRESS_TEST_SUBJECT}/phpinfo.php

  # Create display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

  # Run selenium 2.45.
  - wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar
  - java -jar selenium-server-standalone-2.45.0.jar -p 4444 > ~/selenium.log 2>&1 &
  - sleep 10 # Give Selenium some time to get going

  # Now check we can access the site
#  - curl -s http://local.wordpress.dev/

  # Run behat tests.
  - ${WORDPRESS_SITE_DIR}/wp-content/plugins/${WORDPRESS_TEST_SUBJECT}/vendor/bin/behat -c $WORDPRESS_SITE_DIR/wp-content/plugins/${WORDPRESS_TEST_SUBJECT}/behat.yml

  # Print log ~/phantomjs.log
#  - cat ~/phantomjs.log

  # Print log ~/selenium.log
#  - cat ~/selenium.log
