language: php

php:
  - 5.4

env:
    - WP_VERSION=master WP_MULTISITE=0

addons:
  hosts:
    - local.wordpress.dev

before_install:
  - sudo apt-get update > /dev/null
  - composer self-update
  - WORDPRESS_SITE_DIR="$(dirname $TRAVIS_BUILD_DIR)/wordpress/"
  - WORDPRESS_TEST_SUBJECT=$(basename $TRAVIS_BUILD_DIR)

install:


before_script:
  - ./ci/prepare.sh

script:
  # Create display.
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  - sleep 3 # give xvfb some time to start
#
#  # Run selenium 2.45.
#  - wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar
#  - java -jar selenium-server-standalone-2.45.0.jar -p 4444 > ~/selenium.log 2>&1 &
#  - sleep 5

  # Now check we can access the site
#  - curl -s http://local.wordpress.dev/


  # Run behat tests.
  - ls -al ${TRAVIS_BUILD_DIR}/vendor/bin/
  - ${WORDPRESS_SITE_DIR}/wp-content/plugins/${WORDPRESS_TEST_SUBJECT}/vendor/bin/behat -c $WORDPRESS_SITE_DIR/wp-content/plugins/${WORDPRESS_TEST_SUBJECT}/behat.yml

  # Print log ~/phantomjs.log
#  - cat ~/phantomjs.log

  # Print log ~/selenium.log
#  - cat ~/selenium.log
